// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/core/framework/graph_transfer_info.proto

package org.tensorflow.framework;

public interface GraphTransferNodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GraphTransferNodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 node_id = 2;</code>
   */
  int getNodeId();

  /**
   * <code>optional string type_name = 3;</code>
   */
  java.lang.String getTypeName();
  /**
   * <code>optional string type_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeNameBytes();

  /**
   * <code>optional int32 soc_op_id = 4;</code>
   */
  int getSocOpId();

  /**
   * <code>optional int32 padding_id = 5;</code>
   */
  int getPaddingId();

  /**
   * <code>optional int32 input_count = 6;</code>
   */
  int getInputCount();

  /**
   * <code>optional int32 output_count = 7;</code>
   */
  int getOutputCount();
}
