// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/core/framework/graph_transfer_info.proto

package org.tensorflow.framework;

public interface GraphTransferNodeInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GraphTransferNodeInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 node_id = 1;</code>
   */
  int getNodeId();

  /**
   * <code>optional int32 output_port = 2;</code>
   */
  int getOutputPort();
}
