// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/core/framework/graph_transfer_info.proto

package org.tensorflow.framework;

public interface GraphTransferGraphOutputNodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GraphTransferGraphOutputNodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated int64 shape = 2;</code>
   */
  java.util.List<java.lang.Long> getShapeList();
  /**
   * <code>repeated int64 shape = 2;</code>
   */
  int getShapeCount();
  /**
   * <code>repeated int64 shape = 2;</code>
   */
  long getShape(int index);

  /**
   * <code>optional .tensorflow.DataType dtype = 3;</code>
   */
  int getDtypeValue();
  /**
   * <code>optional .tensorflow.DataType dtype = 3;</code>
   */
  org.tensorflow.framework.DataType getDtype();
}
