// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/core/framework/device_attributes.proto

package org.tensorflow.framework;

public interface InterconnectLinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.InterconnectLink)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>optional string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional int32 strength = 3;</code>
   */
  int getStrength();
}
