// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/core/protobuf/meta_graph.proto

package org.tensorflow.framework;

public final class MetaGraphProtos {
  private MetaGraphProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MetaGraphDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MetaGraphDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MetaGraphDef_MetaInfoDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MetaGraphDef_MetaInfoDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MetaGraphDef_CollectionDefEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MetaGraphDef_CollectionDefEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_MetaGraphDef_SignatureDefEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_MetaGraphDef_SignatureDefEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CollectionDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CollectionDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CollectionDef_NodeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CollectionDef_NodeList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CollectionDef_BytesList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CollectionDef_BytesList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CollectionDef_Int64List_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CollectionDef_Int64List_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CollectionDef_FloatList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CollectionDef_FloatList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CollectionDef_AnyList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CollectionDef_AnyList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TensorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TensorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TensorInfo_CooSparse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TensorInfo_CooSparse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SignatureDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SignatureDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SignatureDef_InputsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SignatureDef_InputsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SignatureDef_OutputsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SignatureDef_OutputsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AssetFileDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_AssetFileDef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#apis/core/protobuf/meta_graph.proto\022\nt" +
      "ensorflow\032\031google/protobuf/any.proto\032\037ap" +
      "is/core/framework/graph.proto\032 apis/core" +
      "/framework/op_def.proto\032&apis/core/frame" +
      "work/tensor_shape.proto\032\037apis/core/frame" +
      "work/types.proto\032\036apis/core/protobuf/sav" +
      "er.proto\"\343\005\n\014MetaGraphDef\022;\n\rmeta_info_d" +
      "ef\030\001 \001(\0132$.tensorflow.MetaGraphDef.MetaI" +
      "nfoDef\022\'\n\tgraph_def\030\002 \001(\0132\024.tensorflow.G" +
      "raphDef\022\'\n\tsaver_def\030\003 \001(\0132\024.tensorflow.",
      "SaverDef\022C\n\016collection_def\030\004 \003(\0132+.tenso" +
      "rflow.MetaGraphDef.CollectionDefEntry\022A\n" +
      "\rsignature_def\030\005 \003(\0132*.tensorflow.MetaGr" +
      "aphDef.SignatureDefEntry\0220\n\016asset_file_d" +
      "ef\030\006 \003(\0132\030.tensorflow.AssetFileDef\032\351\001\n\013M" +
      "etaInfoDef\022\032\n\022meta_graph_version\030\001 \001(\t\022," +
      "\n\020stripped_op_list\030\002 \001(\0132\022.tensorflow.Op" +
      "List\022&\n\010any_info\030\003 \001(\0132\024.google.protobuf" +
      ".Any\022\014\n\004tags\030\004 \003(\t\022\032\n\022tensorflow_version" +
      "\030\005 \001(\t\022\036\n\026tensorflow_git_version\030\006 \001(\t\022\036",
      "\n\026stripped_default_attrs\030\007 \001(\010\032O\n\022Collec" +
      "tionDefEntry\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 \001(\013" +
      "2\031.tensorflow.CollectionDef:\0028\001\032M\n\021Signa" +
      "tureDefEntry\022\013\n\003key\030\001 \001(\t\022\'\n\005value\030\002 \001(\013" +
      "2\030.tensorflow.SignatureDef:\0028\001\"\337\003\n\rColle" +
      "ctionDef\0227\n\tnode_list\030\001 \001(\0132\".tensorflow" +
      ".CollectionDef.NodeListH\000\0229\n\nbytes_list\030" +
      "\002 \001(\0132#.tensorflow.CollectionDef.BytesLi" +
      "stH\000\0229\n\nint64_list\030\003 \001(\0132#.tensorflow.Co" +
      "llectionDef.Int64ListH\000\0229\n\nfloat_list\030\004 ",
      "\001(\0132#.tensorflow.CollectionDef.FloatList" +
      "H\000\0225\n\010any_list\030\005 \001(\0132!.tensorflow.Collec" +
      "tionDef.AnyListH\000\032\031\n\010NodeList\022\r\n\005value\030\001" +
      " \003(\t\032\032\n\tBytesList\022\r\n\005value\030\001 \003(\014\032\036\n\tInt6" +
      "4List\022\021\n\005value\030\001 \003(\003B\002\020\001\032\036\n\tFloatList\022\021\n" +
      "\005value\030\001 \003(\002B\002\020\001\032.\n\007AnyList\022#\n\005value\030\001 \003" +
      "(\0132\024.google.protobuf.AnyB\006\n\004kind\"\240\002\n\nTen" +
      "sorInfo\022\016\n\004name\030\001 \001(\tH\000\0226\n\ncoo_sparse\030\004 " +
      "\001(\0132 .tensorflow.TensorInfo.CooSparseH\000\022" +
      "#\n\005dtype\030\002 \001(\0162\024.tensorflow.DataType\0222\n\014",
      "tensor_shape\030\003 \001(\0132\034.tensorflow.TensorSh" +
      "apeProto\032e\n\tCooSparse\022\032\n\022values_tensor_n" +
      "ame\030\001 \001(\t\022\033\n\023indices_tensor_name\030\002 \001(\t\022\037" +
      "\n\027dense_shape_tensor_name\030\003 \001(\tB\n\n\010encod" +
      "ing\"\240\002\n\014SignatureDef\0224\n\006inputs\030\001 \003(\0132$.t" +
      "ensorflow.SignatureDef.InputsEntry\0226\n\007ou" +
      "tputs\030\002 \003(\0132%.tensorflow.SignatureDef.Ou" +
      "tputsEntry\022\023\n\013method_name\030\003 \001(\t\032E\n\013Input" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022%\n\005value\030\002 \001(\0132\026.ten" +
      "sorflow.TensorInfo:\0028\001\032F\n\014OutputsEntry\022\013",
      "\n\003key\030\001 \001(\t\022%\n\005value\030\002 \001(\0132\026.tensorflow." +
      "TensorInfo:\0028\001\"M\n\014AssetFileDef\022+\n\013tensor" +
      "_info\030\001 \001(\0132\026.tensorflow.TensorInfo\022\020\n\010f" +
      "ilename\030\002 \001(\tBn\n\030org.tensorflow.framewor" +
      "kB\017MetaGraphProtosP\001Z<github.com/tensorf" +
      "low/tensorflow/tensorflow/go/core/protob" +
      "uf\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.tensorflow.framework.GraphProtos.getDescriptor(),
          org.tensorflow.framework.OpDefProtos.getDescriptor(),
          org.tensorflow.framework.TensorShapeProtos.getDescriptor(),
          org.tensorflow.framework.TypesProtos.getDescriptor(),
          org.tensorflow.util.SaverProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_MetaGraphDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_MetaGraphDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MetaGraphDef_descriptor,
        new java.lang.String[] { "MetaInfoDef", "GraphDef", "SaverDef", "CollectionDef", "SignatureDef", "AssetFileDef", });
    internal_static_tensorflow_MetaGraphDef_MetaInfoDef_descriptor =
      internal_static_tensorflow_MetaGraphDef_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_MetaGraphDef_MetaInfoDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MetaGraphDef_MetaInfoDef_descriptor,
        new java.lang.String[] { "MetaGraphVersion", "StrippedOpList", "AnyInfo", "Tags", "TensorflowVersion", "TensorflowGitVersion", "StrippedDefaultAttrs", });
    internal_static_tensorflow_MetaGraphDef_CollectionDefEntry_descriptor =
      internal_static_tensorflow_MetaGraphDef_descriptor.getNestedTypes().get(1);
    internal_static_tensorflow_MetaGraphDef_CollectionDefEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MetaGraphDef_CollectionDefEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_tensorflow_MetaGraphDef_SignatureDefEntry_descriptor =
      internal_static_tensorflow_MetaGraphDef_descriptor.getNestedTypes().get(2);
    internal_static_tensorflow_MetaGraphDef_SignatureDefEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_MetaGraphDef_SignatureDefEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_tensorflow_CollectionDef_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_CollectionDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CollectionDef_descriptor,
        new java.lang.String[] { "NodeList", "BytesList", "Int64List", "FloatList", "AnyList", "Kind", });
    internal_static_tensorflow_CollectionDef_NodeList_descriptor =
      internal_static_tensorflow_CollectionDef_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_CollectionDef_NodeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CollectionDef_NodeList_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_tensorflow_CollectionDef_BytesList_descriptor =
      internal_static_tensorflow_CollectionDef_descriptor.getNestedTypes().get(1);
    internal_static_tensorflow_CollectionDef_BytesList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CollectionDef_BytesList_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_tensorflow_CollectionDef_Int64List_descriptor =
      internal_static_tensorflow_CollectionDef_descriptor.getNestedTypes().get(2);
    internal_static_tensorflow_CollectionDef_Int64List_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CollectionDef_Int64List_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_tensorflow_CollectionDef_FloatList_descriptor =
      internal_static_tensorflow_CollectionDef_descriptor.getNestedTypes().get(3);
    internal_static_tensorflow_CollectionDef_FloatList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CollectionDef_FloatList_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_tensorflow_CollectionDef_AnyList_descriptor =
      internal_static_tensorflow_CollectionDef_descriptor.getNestedTypes().get(4);
    internal_static_tensorflow_CollectionDef_AnyList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CollectionDef_AnyList_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_tensorflow_TensorInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_TensorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TensorInfo_descriptor,
        new java.lang.String[] { "Name", "CooSparse", "Dtype", "TensorShape", "Encoding", });
    internal_static_tensorflow_TensorInfo_CooSparse_descriptor =
      internal_static_tensorflow_TensorInfo_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_TensorInfo_CooSparse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TensorInfo_CooSparse_descriptor,
        new java.lang.String[] { "ValuesTensorName", "IndicesTensorName", "DenseShapeTensorName", });
    internal_static_tensorflow_SignatureDef_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_SignatureDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SignatureDef_descriptor,
        new java.lang.String[] { "Inputs", "Outputs", "MethodName", });
    internal_static_tensorflow_SignatureDef_InputsEntry_descriptor =
      internal_static_tensorflow_SignatureDef_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_SignatureDef_InputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SignatureDef_InputsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_tensorflow_SignatureDef_OutputsEntry_descriptor =
      internal_static_tensorflow_SignatureDef_descriptor.getNestedTypes().get(1);
    internal_static_tensorflow_SignatureDef_OutputsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SignatureDef_OutputsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_tensorflow_AssetFileDef_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_AssetFileDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_AssetFileDef_descriptor,
        new java.lang.String[] { "TensorInfo", "Filename", });
    com.google.protobuf.AnyProto.getDescriptor();
    org.tensorflow.framework.GraphProtos.getDescriptor();
    org.tensorflow.framework.OpDefProtos.getDescriptor();
    org.tensorflow.framework.TensorShapeProtos.getDescriptor();
    org.tensorflow.framework.TypesProtos.getDescriptor();
    org.tensorflow.util.SaverProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
